### ISSUE TITLE
Alternate solution

### ISSUE THREAD

**Issue by sreepathy** [winrid/mongodb-docs-download#1]
No need to take this pain. Download epub from url 
[https://docs.mongodb.com/master/mongodb-manual-master.epub](https://docs.mongodb.com/master/mongodb-manual-master.epub)
and convert it to pdf using calibre or some other tools. This repository is no longer useful.

Old documentation is available here
[http://dl.mongodb.org/dl/docs/](http://dl.mongodb.org/dl/docs/)

**Comment by winrid** [comment]
The link you shared doesn't work. This one seems to: https://docs.mongodb.com/v4.4/mongodb-manual-master.epub

Will review this and update the README.

Interesting that Mongo says they no longer offer the recent docs in a downloadable format...

**Comment by winrid** [comment]
Readme update. Thanks!

**Comment by sreepathy** [comment]
One more link is available. I think this link would have the latest manual since version number is not present in the URL.

https://docs.mongodb.com/manual/mongodb-manual-master.epub
